title: Thiago Mendonça
email: tfariamendonca@gmail.com
description: Histórico profissional e artigos do meu blog pessoal
url: "https://thiagofmendonca.github.io"
baseurl: "" # Importante: string vazia para um repositório de usuário/organização
theme: jekyll-theme-hamilton
skin: midnight

# Outras configurações...
github_username: thiagofmendonca # Pode ser útil para alguns temas

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

paginate: 5
paginate_path: "/artigos/page:num/"

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  # permalinks:
  #   category: "/category/:name/"
  #   tag: "/tag/:name/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Thiago F. Mendonça"
      # Exemplo de capa padrão, ajuste conforme necessário
      # image: /assets/images/default-post-image.jpg
      # comments: true # Habilita comentários por padrão para posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      # comments: false # Desabilita comentários para páginas
  - scope:
      path: "assets/images"
    values:
      feature: true # Exemplo de valor para imagens
